version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    environment:
      - NODE_ENV=production
    volumes:
      - badgr_server_ui:/badgr_server_new_ui
    ports:
      - "4200:4200"
    command: "npm start"